function [lp, grad] = logQjoint(nn,sigma,logF,u,tau,K)

nu = numel(u);
ntau = numel(tau);
u = reshape(u,1,nu);
tau = reshape(tau,1,1,ntau);

u = u(:,:,ones(1,ntau));
tau = tau(:,ones(1,nu),:);

y = logF(tau);
lf = y(1,:,:);
glf = y(2,:,:);

lp =    - (nn-1)*log(u) ...
        - (sigma*K-nn)*log(u+tau) ...
        + (u+tau).^sigma ...
        - tau.^sigma ...
        - lf ...
        + gammaln(nn);
grad = [- (nn-1)./u ...
        - (sigma*K-nn)./(u+tau) ...
        + sigma*(u+tau).^(sigma-1); 
        - (sigma*K-nn)./(u+tau) ...
        + sigma*(u+tau).^(sigma-1) ...
        - sigma*tau.^(sigma-1) ...
        - glf];

end

