
%save data/galaxy.mat galaxy*
%save data/logacid.mat logacid*

fprintf(1,'Conjugate, marginalized & Conditional Slice&\n');
fprintf(1,'%3.1f & %4.0f & %3.1f & %4.0f \\\\\n',...
        galaxyslicecm.runtime,galaxyslicecm.ess(1),...
        logacidslicecm.runtime,logacidslicecm.ess(1));
  
fprintf(1,'Conjugate, marginalized & Marginalized &\n');
fprintf(1,'%3.1f & %4.0f & %3.1f & %4.0f \\\\\n',...
        galaxyneal81cm.runtime,galaxyneal81cm.ess(1),...
        logacidneal81cm.runtime,logacidneal81cm.ess(1));

fprintf(1,'\\hline\n');

fprintf(1,'Conjugate, sampled & Conditional Slice&\n');
fprintf(1,'%3.1f & %4.0f & %3.1f & %4.0f \\\\\n',...
        galaxyslicecs.runtime,galaxyslicecs.ess(1),...
        logacidslicecs.runtime,logacidslicecs.ess(1));

fprintf(1,'Conjugate, sampled & Marginalized ($C$=1) &\n');
fprintf(1,'%3.1f & %4.0f & %3.1f & %4.0f \\\\\n',...
        galaxyneal81cs.runtime,galaxyneal81cs.ess(1),...
        logacidneal81cs.runtime,logacidneal81cs.ess(1));
fprintf(1,'Conjugate, sampled & Marginalized ($C$=2) &\n');
fprintf(1,'%3.1f & %4.0f & %3.1f & %4.0f \\\\\n',...
        galaxyneal82cs.runtime,galaxyneal82cs.ess(1),...
        logacidneal82cs.runtime,logacidneal82cs.ess(1));
fprintf(1,'Conjugate, sampled & Marginalized ($C$=3) &\n');
fprintf(1,'%3.1f & %4.0f & %3.1f & %4.0f \\\\\n',...
        galaxyneal83cs.runtime,galaxyneal83cs.ess(1),...
        logacidneal83cs.runtime,logacidneal83cs.ess(1));
fprintf(1,'Conjugate, sampled & Marginalized ($C$=4) &\n');
fprintf(1,'%3.1f & %4.0f & %3.1f & %4.0f \\\\\n',...
        galaxyneal84cs.runtime,galaxyneal84cs.ess(1),...
        logacidneal84cs.runtime,logacidneal84cs.ess(1));
fprintf(1,'Conjugate, sampled & Marginalized ($C$=5) &\n');
fprintf(1,'%3.1f & %4.0f & %3.1f & %4.0f \\\\\n',...
        galaxyneal85cs.runtime,galaxyneal85cs.ess(1),...
        logacidneal85cs.runtime,logacidneal85cs.ess(1));

fprintf(1,'Conjugate, sampled & Recycled ($C$=1) &\n');
fprintf(1,'%3.1f & %4.0f & %3.1f & %4.0f \\\\\n',...
        galaxyneal8r1cs.runtime,galaxyneal8r1cs.ess(1),...
        logacidneal8r1cs.runtime,logacidneal8r1cs.ess(1));
fprintf(1,'Conjugate, sampled & Recycled ($C$=2) &\n');
fprintf(1,'%3.1f & %4.0f & %3.1f & %4.0f \\\\\n',...
        galaxyneal8r2cs.runtime,galaxyneal8r2cs.ess(1),...
        logacidneal8r2cs.runtime,logacidneal8r2cs.ess(1));
fprintf(1,'Conjugate, sampled & Recycled ($C$=3) &\n');
fprintf(1,'%3.1f & %4.0f & %3.1f & %4.0f \\\\\n',...
        galaxyneal8r3cs.runtime,galaxyneal8r3cs.ess(1),...
        logacidneal8r3cs.runtime,logacidneal8r3cs.ess(1));
fprintf(1,'Conjugate, sampled & Recycled ($C$=4) &\n');
fprintf(1,'%3.1f & %4.0f & %3.1f & %4.0f \\\\\n',...
        galaxyneal8r4cs.runtime,galaxyneal8r4cs.ess(1),...
        logacidneal8r4cs.runtime,logacidneal8r4cs.ess(1));
fprintf(1,'Conjugate, sampled & Recycled ($C$=5) &\n');
fprintf(1,'%3.1f & %4.0f & %3.1f & %4.0f \\\\\n',...
        galaxyneal8r5cs.runtime,galaxyneal8r5cs.ess(1),...
        logacidneal8r5cs.runtime,logacidneal8r5cs.ess(1));


fprintf(1,'\\hline\n');
fprintf(1,'Non-conjugate, sampled& Conditional Slice&\n');
fprintf(1,'%3.1f & %4.0f & %3.1f & %4.0f \\\\\n',...
        galaxyslicens.runtime,galaxyslicens.ess(1),...
        logacidslicens.runtime,logacidslicens.ess(1));

fprintf(1,'Non-conjugate, sampled& Marginalized ($C$=1) &\n');
fprintf(1,'%3.1f & %4.0f & %3.1f & %4.0f \\\\\n',...
        galaxyneal81ns.runtime,galaxyneal81ns.ess(1),...
        logacidneal81ns.runtime,logacidneal81ns.ess(1));
fprintf(1,'Non-conjugate, sampled& Marginalized ($C$=2) &\n');
fprintf(1,'%3.1f & %4.0f & %3.1f & %4.0f \\\\\n',...
        galaxyneal82ns.runtime,galaxyneal82ns.ess(1),...
        logacidneal82ns.runtime,logacidneal82ns.ess(1));
fprintf(1,'Non-conjugate, sampled& Marginalized ($C$=3) &\n');
fprintf(1,'%3.1f & %4.0f & %3.1f & %4.0f \\\\\n',...
        galaxyneal83ns.runtime,galaxyneal83ns.ess(1),...
        logacidneal83ns.runtime,logacidneal83ns.ess(1));
fprintf(1,'Non-conjugate, sampled& Marginalized ($C$=4) &\n');
fprintf(1,'%3.1f & %4.0f & %3.1f & %4.0f \\\\\n',...
        galaxyneal84ns.runtime,galaxyneal84ns.ess(1),...
        logacidneal84ns.runtime,logacidneal84ns.ess(1));
fprintf(1,'Non-conjugate, sampled& Marginalized ($C$=5) &\n');
fprintf(1,'%3.1f & %4.0f & %3.1f & %4.0f \\\\\n',...
        galaxyneal85ns.runtime,galaxyneal85ns.ess(1),...
        logacidneal85ns.runtime,logacidneal85ns.ess(1));

fprintf(1,'Non-conjugate, sampled& Recycled ($C$=1) &\n');
fprintf(1,'%3.1f & %4.0f & %3.1f & %4.0f \\\\\n',...
        galaxyneal8r1ns.runtime,galaxyneal8r1ns.ess(1),...
        logacidneal8r1ns.runtime,logacidneal8r1ns.ess(1));
fprintf(1,'Non-conjugate, sampled& Recycled ($C$=2) &\n');
fprintf(1,'%3.1f & %4.0f & %3.1f & %4.0f \\\\\n',...
        galaxyneal8r2ns.runtime,galaxyneal8r2ns.ess(1),...
        logacidneal8r2ns.runtime,logacidneal8r2ns.ess(1));
fprintf(1,'Non-conjugate, sampled& Recycled ($C$=3) &\n');
fprintf(1,'%3.1f & %4.0f & %3.1f & %4.0f \\\\\n',...
        galaxyneal8r3ns.runtime,galaxyneal8r3ns.ess(1),...
        logacidneal8r3ns.runtime,logacidneal8r3ns.ess(1));
fprintf(1,'Non-conjugate, sampled& Recycled ($C$=4) &\n');
fprintf(1,'%3.1f & %4.0f & %3.1f & %4.0f \\\\\n',...
        galaxyneal8r4ns.runtime,galaxyneal8r4ns.ess(1),...
        logacidneal8r4ns.runtime,logacidneal8r4ns.ess(1));
fprintf(1,'Non-conjugate, sampled& Recycled ($C$=5) &\n');
fprintf(1,'%3.1f & %4.0f & %3.1f & %4.0f \\\\\n',...
        galaxyneal8r5ns.runtime,galaxyneal8r5ns.ess(1),...
        logacidneal8r5ns.runtime,logacidneal8r5ns.ess(1));


